//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdaja_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AkcijskiProizvodi
    {
        public int AkcijskiProizvodID { get; set; }
        public int KorisnikID { get; set; }
        public int ProizvodID { get; set; }
        public decimal Popust { get; set; }
        public System.DateTime DatumPocetka { get; set; }
        public System.DateTime DatumKraja { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
