//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdaja_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Greska
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Greska()
        {
            this.GreskaStavkes = new HashSet<GreskaStavke>();
        }
    
        public int GreskaID { get; set; }
        public string Naziv { get; set; }
        public string Sadrzaj { get; set; }
        public System.DateTime DatumPostavljanja { get; set; }
        public bool Pregledana { get; set; }
        public bool Status { get; set; }
        public int KupacID { get; set; }
    
        public virtual Kupci Kupci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GreskaStavke> GreskaStavkes { get; set; }
    }
}
