//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdaja_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrijedlogKupcaStavke
    {
        public int PrijedlogKupcaStavkaID { get; set; }
        public string Komentar { get; set; }
        public bool Pregledan { get; set; }
        public int KorisnikID { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
    }
}
