//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eProdaja_UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("eProdaja_UI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greska u komunikaciji sa apijem.
        /// </summary>
        internal static string api_error {
            get {
                return ResourceManager.GetString("api_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezan unos naziva.
        /// </summary>
        internal static string cat_name_req {
            get {
                return ResourceManager.GetString("cat_name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorija uspjesno dodata,da li zelite dodati novu?.
        /// </summary>
        internal static string cat_succ {
            get {
                return ResourceManager.GetString("cat_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum mora biti veci ili jednak danasnjem !!.
        /// </summary>
        internal static string datum_err {
            get {
                return ResourceManager.GetString("datum_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno obrisano!.
        /// </summary>
        internal static string del_succ {
            get {
                return ResourceManager.GetString("del_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neispravan format maila.
        /// </summary>
        internal static string email_err {
            get {
                return ResourceManager.GetString("email_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite email.
        /// </summary>
        internal static string email_req {
            get {
                return ResourceManager.GetString("email_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unesite ime.
        /// </summary>
        internal static string fname_req {
            get {
                return ResourceManager.GetString("fname_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne odgovara velicina slike.
        /// </summary>
        internal static string img_size_err {
            get {
                return ResourceManager.GetString("img_size_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno ste obrisali.
        /// </summary>
        internal static string item_del_succ {
            get {
                return ResourceManager.GetString("item_del_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item koji dodajete vec postoji!!.
        /// </summary>
        internal static string item_exist {
            get {
                return ResourceManager.GetString("item_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niste odabrani item.
        /// </summary>
        internal static string item_sel_err {
            get {
                return ResourceManager.GetString("item_sel_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nista dodali ni jedan proizvod!!.
        /// </summary>
        internal static string list_error {
            get {
                return ResourceManager.GetString("list_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesena lozinka nije validna.
        /// </summary>
        internal static string login_pass_err {
            get {
                return ResourceManager.GetString("login_pass_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesna nabavka.
        /// </summary>
        internal static string order_succ {
            get {
                return ResourceManager.GetString("order_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno dodavanje slike !! .
        /// </summary>
        internal static string picture_err {
            get {
                return ResourceManager.GetString("picture_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno dodavanje popusta!!.
        /// </summary>
        internal static string popust_err {
            get {
                return ResourceManager.GetString("popust_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno ste sačuvali podatke.
        /// </summary>
        internal static string product_succ {
            get {
                return ResourceManager.GetString("product_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obavezno unijeti.
        /// </summary>
        internal static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno izbrisano skladiste !!.
        /// </summary>
        internal static string skladiste_del_succ {
            get {
                return ResourceManager.GetString("skladiste_del_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skladiste error.
        /// </summary>
        internal static string skladiste_err {
            get {
                return ResourceManager.GetString("skladiste_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspjesno obavljeno.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dobvljac uspjesno dodan, da li želite dodati jos jednog?.
        /// </summary>
        internal static string sup_succ_info {
            get {
                return ResourceManager.GetString("sup_succ_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
    }
}
